apiVersion: v1
kind: Secret
metadata:
  name: games-secret
type: Opaque
stringData:
  RabbitMq__Username: guest
  RabbitMq__Password: guest
  ElasticSearch__ApiKey: "TGhjSm9Kc0JUU3NrZERjR2s2RjI6YmhIZWR0SEZNdWpuZ0kxeTY5bUtfZw=="
  Jwt__Secret: "KkR.cX]N=8Y3=%uqJJgPD+}K^f?cKnmchVFm-qfa3rUBjBU!G^1L8cn1nEvhv+*"
  ConnectionStrings__DefaultConnection: "Server=games-sqlserver,1433;Database=FiapCloudGamesGames;User Id=sa;Password=Games!Passw0rd;TrustServerCertificate=True"
